-- Create the database
CREATE DATABASE COURSES;
USE COURSES;

-- Create SHORT_COURSE table
CREATE TABLE SHORT_COURSE (
    COURSE_ID VARCHAR(10) PRIMARY KEY,
    COURSE_DESCRIPTION VARCHAR(100) NOT NULL,
    COURSE_PRICE DECIMAL(10,2) NOT NULL
);

-- Create CAMPUS table
CREATE TABLE CAMPUS (
    CAMPUS_ID VARCHAR(10) PRIMARY KEY,
    CAMPUS_NAME VARCHAR(50) NOT NULL,
    CAMPUS_ADDRESS VARCHAR(100) NOT NULL
);

-- Create COURSE_REGISTRATION table (composite primary key)
CREATE TABLE COURSE_REGISTRATION (
    COURSE_ID VARCHAR(10),
    CAMPUS_ID VARCHAR(10),
    SPACES_AVAILABLE INT,
    PRIMARY KEY (COURSE_ID, CAMPUS_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES SHORT_COURSE(COURSE_ID),
    FOREIGN KEY (CAMPUS_ID) REFERENCES CAMPUS(CAMPUS_ID)
);

-- Insert data into SHORT_COURSE
INSERT INTO SHORT_COURSE (COURSE_ID, COURSE_DESCRIPTION, COURSE_PRICE)
VALUES 
    ('CRE101', 'Creative Writing 1', 1500.00),
    ('UIF101', 'User Interface Design 1', 1700.00),
    ('PHO201', 'Photography 2', 2400.00),
    ('STA301', 'Advanced Statistics', 5000.00),
    ('FRE101', 'French for Beginners', 1900.00);

-- Insert data into CAMPUS
INSERT INTO CAMPUS (CAMPUS_ID, CAMPUS_NAME, CAMPUS_ADDRESS)
VALUES 
    ('C001', 'Johannesburg', '167 Pert Road, Johannesburg'),
    ('C002', 'Gqeberha', '5 Second Avenue, Gqeberha'),
    ('C003', 'Bertha Mkhize', '33 Bertha Mkhize Street, Durban'),
    ('C004', 'Durban Campus', '27 Bram Fischer Road, Durban'),
    ('C005', 'Tshwane', '210 Du Toit Street, Tshwane');

-- Insert data into COURSE_REGISTRATION
INSERT INTO COURSE_REGISTRATION (COURSE_ID, CAMPUS_ID, SPACES_AVAILABLE)
VALUES 
    ('UIF101', 'C001', 50),
    ('UIF101', 'C004', 30),
    ('PHO201', 'C005', 15),
    ('STA301', 'C003', 20),
    ('STA301', 'C001', 40);

ALTER TABLE COURSE_REGISTRATION
ADD STUDENTS_REGISTERED INT DEFAULT 0;

UPDATE COURSE_REGISTRATION
SET STUDENTS_REGISTERED = 35
WHERE COURSE_ID = 'STA301' AND CAMPUS_ID = 'C001';

SELECT COURSE_DESCRIPTION AS COURSE_NAME
FROM SHORT_COURSE
LEFT JOIN COURSE_REGISTRATION ON SHORT_COURSE.COURSE_ID = COURSE_REGISTRATION.COURSE_ID
WHERE COURSE_REGISTRATION.COURSE_ID IS NULL;

SELECT 
    SC.COURSE_DESCRIPTION AS COURSE_NAME,
    SUM(CR.SPACES_AVAILABLE) AS "TOTAL SPACES"
FROM SHORT_COURSE SC
LEFT JOIN COURSE_REGISTRATION CR ON SC.COURSE_ID = CR.COURSE_ID
GROUP BY SC.COURSE_ID, SC.COURSE_DESCRIPTION
ORDER BY SC.COURSE_DESCRIPTION ASC;

SELECT TOP 1
    SC.COURSE_DESCRIPTION AS COURSE_NAME,
    C.CAMPUS_NAME,
    CR.SPACES_AVAILABLE
FROM COURSE_REGISTRATION CR
JOIN SHORT_COURSE SC ON CR.COURSE_ID = SC.COURSE_ID
JOIN CAMPUS C ON CR.CAMPUS_ID = C.CAMPUS_ID
WHERE CR.COURSE_ID = 'STA301'
ORDER BY CR.SPACES_AVAILABLE DESC;